apiVersion: v1
kind: Secret
metadata:
  name: mysql-task-pass 
data:
  password: {{ .Values.secret.value | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.wordPass }} 
data:
  password: {{ .Values.wordpressSecret.value | b64enc | quote }}

